In [1]:
import torch
print(torch.__version__) 

1.2.0


In [2]:
a = torch.ones(5)

In [15]:
a

tensor([1., 1., 1., 1., 1.])

In [7]:
a.size()

torch.Size([5])

In [8]:
b = a.unsqueeze(0)

In [13]:
b

tensor([[1., 1., 1., 1., 1.]])

In [9]:
b.size()

torch.Size([1, 5])

In [10]:
c = a.unsqueeze(1)

In [11]:
c.size()

torch.Size([5, 1])

In [12]:
c

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [17]:
g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])

In [23]:
g

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [18]:
g.size()

torch.Size([2, 2, 2])

In [20]:
f = g.unsqueeze(0)

In [21]:
f.size()

torch.Size([1, 2, 2, 2])

In [25]:
h = g.unsqueeze(1)

In [26]:
h.size()

torch.Size([2, 1, 2, 2])

In [46]:
x = torch.rand(1,1,5)

In [47]:
x.size()

torch.Size([1, 1, 5])

In [48]:
x

tensor([[[0.0936, 0.4730, 0.5537, 0.7990, 0.6612]]])

In [50]:
y=  x.expand(1,3,-1)

In [51]:
y.size()

torch.Size([1, 3, 5])

In [52]:
y

tensor([[[0.0936, 0.4730, 0.5537, 0.7990, 0.6612],
         [0.0936, 0.4730, 0.5537, 0.7990, 0.6612],
         [0.0936, 0.4730, 0.5537, 0.7990, 0.6612]]])